### PR TITLE
handle vscode special vars in cmake.*environment options

### PR DESCRIPTION
**Pull request by dcourtois**
Related to issue #193 
I had the time to take a closer look at the source code, and I noticed that a function was already existing : common.replaceVars. So I put that in util.ts, and in config.ts I created a private function to apply this to all the values in environment objects.

Unfortunately, I couldn't test anything because I don't know how to setup VSCode to compile this extension and then install / test it ... so I hope you can take a look and tell me how to proceed from here :) I'm willing to rework the pull request (if I don't follow the coding style, if I did something not recommended, etc.) so don't hesitate to tell me if there's something wrong !

### CODE REVIEW

**Comment by vector-of-bool** [comment]
Thanks for the input! The PR won't work as-is (There's a usage of `this` in `replaceVars` that won't play nice). I'll see about adding the functionality in the next release version.

**Comment by dcourtois** [comment]
Hi, thanks for taking the time to check this ! Is there any documentation on how to work on the extension ? (what tool to install, how to compile, run tests, etc.)
I would love to help (I'm also in need of feature #128 :p)

**Comment by ytimenkov** [comment]
Fairly simple. I think it's better to install nodejs, then typescript globally:
~~~
npm install -g typescript
~~~
then after checking out cmake tools repo, locally
~~~
npm install
~~~
this downloads packages mentioned in package.json (think of nuget restore).

then just select "run extension" in vs code.

I suggest checking [VS Code documentation](https://code.visualstudio.com/docs/extensions/example-hello-world), it's good.

For typescript I like [this one](https://basarat.gitbooks.io/typescript/content/docs/getting-started.html) much more compact than [official handbook](https://www.typescriptlang.org/docs/handbook/basic-types.html), and just gives answers.

That what I used. Didn't know anything about typescript 2 weeks ago :D

**Comment by dcourtois** [comment]
Aha ! was missing the `npm install` instruction, thanks !! Thanks to that, I could check my modification, and it seems it works fine: I only had a small fix to replaceVars to make, and it compiles correctly, and works well on my test project.

**Comment by ntwerdochlib** [comment]
@ytimenkov Perhaps the setup you described previously regarding the steps required to build the code from the repo should be documented somewhere?  Not a TypeScripter myself but want to make some changes and was unable to build the code until I stumbled upon your reply.

**Comment by vector-of-bool** [comment]
@dcourtois, I think it's odd that it compiled for you... since the unbound `this` in `replaceVars` should have made sadness. Huh...

I think having a new `CONTRIBUTING.md` doc would be great.

TypeScript isn't hard to learn at all. With a good editor like VSCode, it pretty much holds your hand the whole way until you get used to it on your own. This extension is actually my first TypeScript project, and it seems to have turned out pretty well :smile:

**Comment by dcourtois** [comment]
Agreed for the `contributing.md` file. And for the problem in replaceVars, I probably didn't have the error because I'm not using the `${buildType}` which is what is using `this`.

**Comment by dcourtois** [comment]
Hi again, see my last commit for a way of fixing this : since some variable depends on the actual cmake stuff (such as buildType) and other do not (variables accessing generic config or workspace stuff) I split the replaceVars in 2 functions: one in util.ts and one in common.ts

This way, no more problems, and the util.ts one can be used everywhere needed.

I ran the tests also, but it generated an exception in client.ts, at a place that seemed totally unrelated to the modifications I did, so I'm not sure what to do of that.

**Comment by dcourtois** [comment]
Hi, any news on this ?? I'm willing to work on that, so don't hesitate to tell me if there's anything wrong (from code convention to naming, architecture, whatever) :)

**Comment by vector-of-bool** [comment]
@dcourtois, sorry for the delay. I'll see about getting this released before the day is done.

**Comment by dcourtois** [comment]
Howesome, thanks a lot !
(and now worries, I was just asking to know if I needed more work on the PR, I know time can be a problem :))

**Pull request merged**
