### PR TITLE
Add config "outputLogEncoding"

### PR DESCRIPTION
**Pull request by pengbins**
This change try to fix a codepage problem mentioned in some issues, such as  #518 , #267 ,  #245 and #153. 
The output messages of cmake build command are garbled when  the default system codepage is not utf8.

It is fixed by adding a user config item "outputEncoding" to set the character encoding of messages in the output console.  

- How to use
    * Set "outputEncoding" to your system default codepage. (Ctrl+,  and search outputEncoding)
image
    * The default value is "utf8".  For Chinese user, set it to "GBK".  
    * Supported value list can be found [here](https://github.com/ashtuchkin/iconv-lite#supported-encodings) .
- Results
    * Output console used to be unreadable when the default system codepage is not utf8.
image
    * Output console is readable after set "outputEncoding" to  GBK.
image

- How it works
This change introduces a new dependency   [iconv-lite](https://github.com/ashtuchkin/iconv-lite).
The console programs emit text encoded with the default system codepage. This change uses iconv-lite to decode those text to utf8 , so they can be  displayed correctly on output console. To decode,  iconv-lite
needs to know the default system codepage which is given by  user's config "outputEncoding".

### CODE REVIEW

**Comment by vector-of-bool** [comment]
This change is excellent!!

The output codepage issues has been persistently troublesome almost from the very beginning. I've been unable to test and was never sure how to approach this problem.

One think I am wondering is if there is the possibility to auto-detect the code page. I found that Windows exposes a `_CODEPAGE` environment variable for the current codepage number. I've found a table of these numbers to their names, but I don't think the names that microsoft provides will work with `iconv-lite`.

Instead of trying to get them all down immediately, could you add a lookup that uses the `_CODEPAGE` value to default to your `GBK` when `_CODEPAGE` is the value you have on your system? As users report this issue I can add entries to this table so that people won't have to manually change their encoding.

**Comment by vector-of-bool** [comment]
Alternatively, you could try using this table I made from codepage number to names. Maybe iconv just supports it out-of-the box? That would be awesome, and changing the output encoding setting wouldn't ever be required.

[code-pages.ts.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/2453670/code-pages.ts.txt)

**Comment by pengbins** [comment]
> **Last question:** Can you verify that the auto-detection works on your system?
Yes, it works on my system. But I didn't test on other language system except mine.
My code page number is 936, encoding name is gb2312.

**Comment by nim** [comment]
Problem is still here

**Comment by Randshot** [comment]
@nim Can you please open a separate issue for this. It's easier to track that way :)

**Comment by nim** [comment]
https://github.com/Microsoft/vscode/issues/72270

**Pull request merged**
