### PR TITLE
parse vswhere output from text format due to i18n encoding problem.

### PR DESCRIPTION
**Pull request by itn3000**
### This changes

The following changes are proposed:

- parse vswhere output from "text" format instead of JSON.parse()

## The purpose of this change

As a premise, JSON.parse()  throws error if invalid character is found in input string.
Invalid character is almost in "Description" element.
but VsWhereItem only needs  "installationVersion", "installationPath", "displayName",
so "Description" element can be just ignored.

JSON.parse does not have "ignore invalid sequence" option, so I changed to use text format.

## Other Notes/Information

this is little bit unstable way(because it depends on vswhere output).
Please tell me if there is more efficient and stable way.

### CODE REVIEW

**Comment by vector-of-bool** [comment]
Sorry for the month of silence. I'm now getting back into the flow of things and cleaning up the project.

I remember a much earlier issue involving the output locale when invoking VSWhere.exe. I made a comment somewhere in the vswhere repo asking about this and was told that setting a certain option would fix the JSON output to contain the properly encoded characters.

**Comment by itn3000** [comment]
Actually, I made the PR(https://github.com/Microsoft/vswhere/pull/132) to solve the #220, but I haven't been able to give the persuasive explanation to merge the PR.
For accepting the PR, I must make good explanation. It may be needed to take more time.
So, I decide to make adhoc PR for this extension to use in non-ascii environment anyway.

**Comment by Randshot** [comment]
Since this is out of date, I will close this PR.

**Comment by vector-of-bool** [comment]
@itn3000, we have a possible fix that will be available in beta5

**Pull request closed without merging**
