### PR TITLE
New Test Runner

### PR DESCRIPTION
**Pull request by vector-of-bool**
This PR introduces a new test runner specializing in what is needed for CMake Tools. This takes advantage of some recent refactorings to run CMakeTools without any mocks or fixtures. The test runner class sets up a project directory from a set of templates and runs the `test.ts` file contained within each respective test directories.

It also includes some new basic smoke tests using this test runner.

### CODE REVIEW

**Comment by vector-of-bool** [comment]
@KoeMai I'm wanting to get all tests working without significant mocking. This is the first step in that direction. Each smoke test group is contained in a different subdirectory of the `test/smoke` dir, and they all run their own `test.ts` with a set of CMakeLists.txt and other source files. The goal is that arbitrarily complex CMake projects can be contained in these directories to test every aspect of the ext that we want.

**Comment by KoeMai** [comment]
Sorry for my late response. I think cmake does not find any compiler witch works with ninja.

I tried following commandline parts on my PC:

```
$ cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe -- works-- Detecting C compiler ABI info-- Detecting C compiler ABI info - done-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features-- Detecting CXX compile features - done
-- Configuring done-- Generating done
-- Build files have been written to: C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build
```

```
test+test@test MINGW64 ~/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build (feature/custom-testrunner-2)
$ cmake .. -G "Ninja"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeError.log".
```

```
test+test@test MINGW64 ~/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build (feature/custom-testrunner-2)
$ cmake .. -G "Unix Makefiles"
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeOutput.log".
```

```
test+test@test MINGW64 ~/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build (feature/custom-testrunner-2)
$ cmake .. -G "MinGW Makefiles"
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/Program Files/Git/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

```
test+test@test MINGW64 ~/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build (feature/custom-testrunner-2)
$ cmd
Microsoft Windows [Version 10.0.17134.81]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.
```

```
vscode-cmake-tools\test\smoke\_project-dir\build>cmake .. -G "MinGW Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/MinGW/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeTmp

    Run Build Command:"C:/MinGW/bin/mingw32-make.exe" "cmTC_ea1bf/fast"
    C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_ea1bf.dir\build.make CMakeFiles/cmTC_ea1bf.dir/build
    mingw32-make.exe[1]: Entering directory 'C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_ea1bf.dir/testCCompiler.c.obj
    C:\MinGW\bin\gcc.exe    -o CMakeFiles\cmTC_ea1bf.dir\testCCompiler.c.obj   -c vscode-cmake-tools\test\smoke\_project-dir\build\CMakeFiles\CMakeTmp\testCCompiler.c
    CMakeFiles\cmTC_ea1bf.dir\build.make:64: recipe for target 'CMakeFiles/cmTC_ea1bf.dir/testCCompiler.c.obj' failed
    mingw32-make.exe[1]: *** [CMakeFiles/cmTC_ea1bf.dir/testCCompiler.c.obj] Error 1
    mingw32-make.exe[1]: Leaving directory 'C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeTmp'
    Makefile:120: recipe for target 'cmTC_ea1bf/fast' failed
    mingw32-make.exe: *** [cmTC_ea1bf/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/test/Downloads/vscode-cmake-tools/test/smoke/_project-dir/build/CMakeFiles/CMakeError.log".
```

```
vscode-cmake-tools\test\smoke\_project-dir\build>dir c:\Mingw\bin


 Verzeichnis von c:\Mingw\bin

...
05.10.2013  19:17         1.821.710 g++.exe
05.10.2013  19:17            65.550 gcc-ar.exe
05.10.2013  19:17            65.038 gcc-nm.exe
05.10.2013  19:17            65.038 gcc-ranlib.exe
05.10.2013  19:17         1.819.150 gcc.exe
...
04.10.2013  21:20            52.224 mingw-get.exe
05.10.2013  19:17         1.821.710 mingw32-c++.exe
05.10.2013  19:17         1.819.150 mingw32-cc.exe
05.10.2013  19:17         1.821.710 mingw32-g++.exe
05.10.2013  19:17         1.819.150 mingw32-gcc-4.8.1.exe
05.10.2013  19:17            65.550 mingw32-gcc-ar.exe
05.10.2013  19:17            65.038 mingw32-gcc-nm.exe
05.10.2013  19:17            65.038 mingw32-gcc-ranlib.exe
05.10.2013  19:17         1.819.150 mingw32-gcc.exe
02.09.2012  02:42           219.662 mingw32-make.exe
...
             126 Datei(en),     78.777.982 Bytes
               2 Verzeichnis(se), 151.451.652.096 Bytes frei
```

```
vscode-cmake-tools\test\smoke\_project-dir\build>set PATH=c:\MinGw\bin;%PATH%
```

```
vscode-cmake-tools\test\smoke\_project-dir\build>cmake .. -G "MinGW Makefiles"
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: vscode-cmake-tools/test/smoke/_project-dir/build
```

After the commandline testings i tried this in the settings file:
 "cmake.environment": {"PATH": "c:\\MinGW\\bin;${env:PATH}"}

Now it works, I think the PATH variable on appveyor is wrong.

I do not know how to set the PATH in the smoke test testsuite.

**Comment by vector-of-bool** [comment]
That's odd. The new tests shouldn't _need_ Ninja... I'm confused here.

**Comment by vector-of-bool** [comment]
@KoeMai I got on my Windows and was able to figure out what's happening. You're right: It can't find a kit. I told the test to use the special `__unspec__` kit, but that doesn't work if there is no compiler on the `$PATH`. I've modified the smoke tests to load a VS kit when running on Windows.

**Comment by vector-of-bool** [comment]
I've fixed(-ish) the Windows build. VS 2015 is still failing for unrelated reasons. @KoeMai would you give this a look and tell me what you think of the changes?

**Pull request merged**
